### ISSUE TITLE
Video Preview size changes when cloning/dragging around in columns

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Page-Builder-Sandwich#112]
Cloning: http://i.imgur.com/T4ALc34.png
2 Videos in 2 Columns: http://i.imgur.com/Qpe9zNQ.png
2 Videos in 3 Columns: http://i.imgur.com/5k1lkm2.png

**Comment by bfintal** [comment]
Fixed 80229443a1cf6e61b2c107c91f03d542b6d8fb2b
