### ISSUE TITLE
can't insert post element

### ISSUE THREAD

**Issue by closeupman** [gambitph/Page-Builder-Sandwich#117]
I tried to select and insert...but nothing happens.

**Comment by oherman** [comment]
WordPress version, theme being used and PB Sandwich version?
Is your page editor fully loaded?

**Comment by bfintal** [comment]
@closeupman will need more information on that

**Comment by bfintal** [comment]
Occasionally happens with the javascript error **cannot find nextSibling**, this is a Shortcake issue, but we should try and fix it

**Comment by bfintal** [comment]
`Uncaught TypeError: Cannot read property 'previousSibling' of null`

There's a core ticket regarding this: https://core.trac.wordpress.org/ticket/29216

**Comment by bfintal** [comment]
No longer need to fix this since it seems that it's fixed in WP 4.2
