### ISSUE TITLE
Soliloquy Conflict

### ISSUE THREAD

**Issue by riceguitar** [gambitph/Page-Builder-Sandwich#118]
Using the Soliloquy slider plugin for Wordpress. When PBS is active the "Add Slider" editor button no longer responds or pops up. Perhaps reach out to @thomasgriffin

**Comment by bfintal** [comment]
Thanks, will do

**Comment by bfintal** [comment]
Verified working now in WP 4.2, Sandwich 1.1 and Soliloquy 2.3.0
