### ISSUE TITLE
Use a grid system instead of percentages.

### ISSUE THREAD

**Issue by bfintal** [gambitph/Page-Builder-Sandwich#13]
**Effects**

* Either don't do #6 anymore, or handle both and #6 would override the grid

**Pros**

* More standard approach
* No more inlined styles

**Cons**

* Styles may clash with themes with GS

**Comment by SiamKreative** [comment]
I'm all in for a standardized grid system. With proper CSS prefixing, I don't see how it could possibly conflict with a theme's grid.

**Comment by bfintal** [comment]
Should we go with Bootstrap so we can also make use of other components such as buttons for including shortcodes?
