### ISSUE TITLE
Empty Paragraph Tags Being Added

### ISSUE THREAD

**Issue by abaney** [gambitph/Page-Builder-Sandwich#131]
As you can see, I highlighted the yellow paragraph `<p>` tags in the image below. The empty yellow boxes are extra, empty paragraph tags that were added to my content (ignore the circles / dots all over the place).

Is this a glitch that can be fixed?

![emptyparagraphs](https://cloud.githubusercontent.com/assets/2255186/7193113/aca59fa8-e459-11e4-977b-e63cdfd65466.png)

Also, I have <a href="https://wordpress.org/support/topic/remove-disable-post-elements">another issue</a> and a <a href="https://wordpress.org/support/topic/vertical-align-center">possible bug fix</a> with this plugin on the <a href="http://wordpress.org/">WordPress</a> site. Would you prefer that I transfer those to GitHub?

Thank you!

**Comment by bfintal** [comment]
Hey, sure please do transfer them in.

Version 1.0 is just around the corner, it comes with a ton of stability fixes. This empty paragraphs isn't resolved yet, but I'm just about to tackle this.

**Comment by abaney** [comment]
@bfintal - Thanks so much for adding this to your "bug fix" list! I noticed that you also ported my other issue to GitHub. Thank you! I'm still pretty-much sold on using your plugin.  ;)

**Comment by bfintal** [comment]
@abaney fixed, you can test it out using the master copy :)

**Comment by abaney** [comment]
Tested, and you totally fixed this issue! You're amazing, @bfintal !

**Comment by bfintal** [comment]
@abaney :+1:
