### ISSUE TITLE
Raw PHP shortcake?

### ISSUE THREAD

**Issue by oherman** [gambitph/Page-Builder-Sandwich#134]
Use this: https://wordpress.org/plugins/insert-php-code-snippet/
Or make our own?

This sounds crazy but with such presence of plugins, I think PB Sandwich needs its own implementation too.

Visualised workflow:

[pb-php]raw php code here[/pb-php]

eval($content)

**Comment by bfintal** [comment]
`eval` is pretty much discouraged is a huge security risk
