### ISSUE TITLE
"The plugin does not have a valid header." error when activating after install

### ISSUE THREAD

**Issue by pelmered** [gambitph/Page-Builder-Sandwich#136]
When I installed the plugin(by searching and clicking install in WP-Admin) and then activated it I got this error:

"The plugin does not have a valid header."

The plugin was successfully activated when I later on activated it from the plugins list.

**Comment by bfintal** [comment]
Thanks! I think this might be caused by the Shortcake headers that were included. I've removed them in 9a65c89d7156c16862064392ac2945f24606ac27 and will be pushing out v1.0.1 soon
