### ISSUE TITLE
Font Awesome shortcode would be useful

### ISSUE THREAD

**Issue by donnafontenot** [gambitph/Page-Builder-Sandwich#152]
Quite often, columns contain features such as lists that would benefit from the use of font awesome icons. The ability to see the icons, rather than just shortcode code, would be a nice benefit. For example, let's say I was going to display a couple of columns of product benefits in a list style format. Each benefit would be preceded by a font awesome checkmark or perhaps an icon that represents that feature. Seeing it visually, rather than just seeing [fa fa-check] or something similar would be useful. Thanks.

**Comment by bfintal** [comment]
Hey @donnafontenot yea, icons would be a great addition :+1: 

It would be a good experience if there is a search functionality when placing an icon. That would probably be the one of the hardest things to implement. We're releasing version 1.1 soon, that will address a lot of stability issues. Icons will most probably make it in 1.2 :)
