### ISSUE TITLE
Parse error: syntax error, unexpected T_FUNCTION 

### ISSUE THREAD

**Issue by seahum01** [gambitph/Page-Builder-Sandwich#160]
I downloaded the plugin to my wordpress site and when i activated the plugin, i get the following error and now cannot access any part of my site: 

Parse error: syntax error, unexpected T_FUNCTION in /home/content/38/8992138/html/main/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35

How do i resolve this? How do i delete/deactivate the plug-in when i can't even load the back-end of my site?

**Comment by oherman** [comment]
May I know your wordpress and PHP version? Errors like that are usually given by outdated PHP.
To deactivate it manually, log in to your ftp and rename the page builder sandwich folder.

**Comment by seahum01** [comment]
3.4.2 WP - can't remember the PHP version and have never logged into the ftp before (pretty basic user relatively speaking)- trying to figure that out at the moment.

**Comment by seahum01** [comment]
resolved: i renamed the page builder sandwich folder and then deleted the plugin. it would appear i need to update my WP and PHP version before trying this plugin again. thanks.

**Comment by oherman** [comment]
Let us know if you have more questions, we'll be glad to answer them.
