### ISSUE TITLE
Duplicated shortcode inside Column

### ISSUE THREAD

**Issue by edoutorresjr** [gambitph/Page-Builder-Sandwich#161]
Hello,

To reproduce the issue:
- in Visual Mode, insert a "1 column" table
- with the cursor inside the column, click on the "Add Post Element" button, select the Button shortcode,  set its hover color parameters and insert it
- just after the button, click on the  "Add Post Element" button to insert another shortcode, for example a toggle.
- as a result, you'll see that the first button shortcode is duplicated when you insert the toggle

I tried to search where's the issue, it seems that it happens only when the shortcode has the `<style></style>` tag inside its view and when you are placed inside a column.

For example my button has the following code inside its view:
`<style>#pbs_button-1:hover {border-color: #383838 !important; }</style>`

If I remove this styling code inside the sandwich_buttons_shortcode() function, there's no issue.
And if you are outside a table, there's no issue neither.

**Comment by bfintal** [comment]
Thanks for the report. I can replicate with the steps you gave.

Best way would probably move the styling inline instead of a standalone `style` tag

**Comment by bfintal** [comment]
We cannot do this inline since the `style` tag is for a `:hover` rule. However, adding `data-mce-bogus="1"` to the `<style>` fixes the issue
