### ISSUE TITLE
Page Builder Sandwich crashes website on activation.

### ISSUE THREAD

**Issue by designbypepper** [gambitph/Page-Builder-Sandwich#162]
I've tried twice to add Page Builder Sandwich but it crashes my website on activation. Hostmonster/bluehost mojomarketplace installation of wordpress.

I really need this to work.

**Comment by oherman** [comment]
PHP and WordPress version?

**Comment by designbypepper** [comment]
HostMonster Web Hosting Help
PHP Version Selection (PHP Config)
All our servers support (i.e. are capable of running) PHP 5.2 and PHP 5.4. The default version is 5.4.x 

WordPress
Version 4.2.1

**Comment by oherman** [comment]
Okay, upgrade your WordPress and ensure you can run PHP higher than 5.3.
If the website still crashes on activation, please paste here the error
message.

**Comment by designbypepper** [comment]
The default verson is 5.4   and wordpress is updated to 4.2.1 (there is no newer version)

There is no error message, it just crashes the website, i had to reinstall wordpress 3 times now.

**Comment by designbypepper** [comment]
there is no error message. 

  when activated,  it goes blank, no page is displayed and you cannot even get to the admin panel.

**Comment by oherman** [comment]
I think your webhost has disabled error messages. Do you have access to
error logs? We need to at least see the error messages being thrown.
I assume you've tried also reuploading the plugin, right?

**Comment by designbypepper** [comment]
3 times.  the error log is erased everytime i re-install wordpress.  so i will need to activate the plug in one more time (4th time).  it will be just a few min.

**Comment by designbypepper** [comment]
Successfully installed the plugin Page Builder Sandwich 1.1.

now i will activate

page is redircted to ..//wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=

the website is down

will look for error log now.

**Comment by bfintal** [comment]
This usually happens when the server runs out of memory. Or when there's a wandering white space in wp-config.php. It can also mean there's a 500 error that occurs.

Will need to get some error logs to find out what the problem really is. Try putting this in your wp-config:
```
error_reporting(E_ALL); ini_set('display_errors', 1);
define( 'WP_DEBUG', true);
```

source: https://wordpress.org/support/topic/blank-screen-after-activatingdeleting-plugins?replies=13

If Sandwich is the one that errors out and causes the blank screen, you can bring back the menu by FTPing and renaming Sandwich's folder in `wp-content/plugins/` to another name. That should deactivate it.

**Comment by designbypepper** [comment]
when i tried to access the error.log it crashed my ftp program, i don't
think i can view the log this way.


On Wed, Apr 29, 2015 at 4:57 PM, Benjamin Intal <notifications@github.com>
wrote:

> This usually happens when the server runs out of memory. Or when there's a
> wandering white space in wp-config.php. It can also mean there's a 500
> error that occurs.
>
> Will need to get some error logs to find out what the problem really is.
> Try putting this in your wp-config:
>
> error_reporting(E_ALL); ini_set('display_errors', 1);
> define( 'WP_DEBUG', true);
>
> source:
> https://wordpress.org/support/topic/blank-screen-after-activatingdeleting-plugins?replies=13
>
> If Sandwich is the one that errors out and causes the blank screen, you
> can bring back the menu by FTPing and renaming Sandwich's folder in
> wp-content/plugins/ to another name. That should deactivate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97617043>
> .
>



-- 
www.DesignByPepper.com

**Comment by bfintal** [comment]
Found this: https://my.hostmonster.com/cgi/help/562

**Comment by designbypepper** [comment]
thanks for the tip on restoring my website, at least i don't have to keep
reinstalling wordpress.
I will see what the error log says


On Wed, Apr 29, 2015 at 5:03 PM, Benjamin Intal <notifications@github.com>
wrote:

> Found this: https://my.hostmonster.com/cgi/help/562
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97617655>
> .
>



-- 
www.DesignByPepper.com

**Comment by bfintal** [comment]
No problem, I also want to know what is happening here for future cases. In an incorrect PHP version or a lower WordPress version shouldn't bog down the site and should only cause an activation warning. So there must be something else going on

**Comment by designbypepper** [comment]
I understand you need to find out why this is happening.  I am lost trying
to get to the error log, i have never done this before.
This is over my head. I may need to contact hostmonster but i don't know
what to ask them exactly.

On Wed, Apr 29, 2015 at 5:08 PM, Benjamin Intal <notifications@github.com>
wrote:

> No problem, I also want to know what is happening here for future cases.
> In an incorrect PHP version or a lower WordPress version shouldn't bog down
> the site and should only cause an activation warning. So there must be
> something else going on
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97618181>
> .
>



-- 
www.DesignByPepper.com

**Comment by oherman** [comment]
I would start by asking for the most recent error logs because they're too
big for any text program to digest.
Tell them you're trying to track down a PHP script that's been crashing.

**Comment by oherman** [comment]
Also did you try the suggestion Benjamin said about adding certain lines in
wp-config.php?

That might display the error right out of the bat.

**Comment by designbypepper** [comment]
I did not edit the wp config php file yet.  the error log is huge i'm
trying to find the error for my site, shared hosting lots of errors but not
mine.

On Wed, Apr 29, 2015 at 5:17 PM, oherman <notifications@github.com> wrote:

> Also did you try the suggestion Benjamin said about adding certain lines in
> wp-config.php?
>
> That might display the error right out of the bat.
>
>
> On Thu, Apr 30, 2015 at 8:14 AM, Herman Near <oherman@gmail.com> wrote:
>
> > I would start by asking for the most recent error logs because they're
> too
> > big for any text program to digest.
> > Tell them you're trying to track down a PHP script that's been crashing.
> >
> > On Thu, Apr 30, 2015 at 8:12 AM, designbypepper <
> notifications@github.com>
> > wrote:
> >
> >> I understand you need to find out why this is happening. I am lost
> trying
> >> to get to the error log, i have never done this before.
> >> This is over my head. I may need to contact hostmonster but i don't know
> >> what to ask them exactly.
> >>
> >> On Wed, Apr 29, 2015 at 5:08 PM, Benjamin Intal <
> notifications@github.com
> >> >
> >> wrote:
> >>
> >> > No problem, I also want to know what is happening here for future
> cases.
> >> > In an incorrect PHP version or a lower WordPress version shouldn't bog
> >> down
> >> > the site and should only cause an activation warning. So there must be
> >> > something else going on
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97618181
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> www.DesignByPepper.com
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97618500
> >
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97619026>
> .
>



-- 
www.DesignByPepper.com

**Comment by designbypepper** [comment]
added the lines of code to wpconfig.php and got this message when
activating your plugin
*Notice*: Constant WP_DEBUG already defined in
*/home1/designc6/public_html/acceleratedheating/wp-config.php* on line *92*

On Wed, Apr 29, 2015 at 5:17 PM, oherman <notifications@github.com> wrote:

> Also did you try the suggestion Benjamin said about adding certain lines in
> wp-config.php?
>
> That might display the error right out of the bat.
>
>
> On Thu, Apr 30, 2015 at 8:14 AM, Herman Near <oherman@gmail.com> wrote:
>
> > I would start by asking for the most recent error logs because they're
> too
> > big for any text program to digest.
> > Tell them you're trying to track down a PHP script that's been crashing.
> >
> > On Thu, Apr 30, 2015 at 8:12 AM, designbypepper <
> notifications@github.com>
> > wrote:
> >
> >> I understand you need to find out why this is happening. I am lost
> trying
> >> to get to the error log, i have never done this before.
> >> This is over my head. I may need to contact hostmonster but i don't know
> >> what to ask them exactly.
> >>
> >> On Wed, Apr 29, 2015 at 5:08 PM, Benjamin Intal <
> notifications@github.com
> >> >
> >> wrote:
> >>
> >> > No problem, I also want to know what is happening here for future
> cases.
> >> > In an incorrect PHP version or a lower WordPress version shouldn't bog
> >> down
> >> > the site and should only cause an activation warning. So there must be
> >> > something else going on
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97618181
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> www.DesignByPepper.com
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97618500
> >
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97619026>
> .
>



-- 
www.DesignByPepper.com

**Comment by bfintal** [comment]
In the default config there's a 
```define('WP_DEBUG', false);```
there, so you'll have to remove that. And replace it with
```error_reporting(E_ALL); ini_set('display_errors', 1);
define( 'WP_DEBUG', true);```

**Comment by designbypepper** [comment]
from error log

[27-Apr-2015 23:13:22] PHP Parse error:  syntax error, unexpected
T_FUNCTION in /home1/designc6/public_html/mesotheliomavictimscenter/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php
on line 35


On Wed, Apr 29, 2015 at 5:31 PM, Benjamin Intal <notifications@github.com>
wrote:

> In the default config there's a
> define('WP_DEBUG', false);
> there, so you'll have to remove that. And replace it with
> error_reporting(E_ALL); ini_set('display_errors', 1);
> define( 'WP_DEBUG', true);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97620430>
> .
>



-- 
www.DesignByPepper.com

**Comment by designbypepper** [comment]
that was a few days ago when i tried on another site, let me get today's
error, probably the same


On Wed, Apr 29, 2015 at 5:36 PM, Pepper <pepperwarren@gmail.com> wrote:

> from error log
>
> [27-Apr-2015 23:13:22] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/mesotheliomavictimscenter/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>
>
> On Wed, Apr 29, 2015 at 5:31 PM, Benjamin Intal <notifications@github.com>
> wrote:
>
>> In the default config there's a
>> define('WP_DEBUG', false);
>> there, so you'll have to remove that. And replace it with
>> error_reporting(E_ALL); ini_set('display_errors', 1);
>> define( 'WP_DEBUG', true);
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97620430>
>> .
>>
>
>
>
> --
> www.DesignByPepper.com
>



-- 
www.DesignByPepper.com

**Comment by designbypepper** [comment]
here is today's error


[30-Apr-2015 00:29:02] PHP Parse error:  syntax error, unexpected
T_FUNCTION in /home1/designc6/public_html/acceleratedheating/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php
on line 35


On Wed, Apr 29, 2015 at 5:39 PM, Pepper <pepperwarren@gmail.com> wrote:

> that was a few days ago when i tried on another site, let me get today's
> error, probably the same
>
>
> On Wed, Apr 29, 2015 at 5:36 PM, Pepper <pepperwarren@gmail.com> wrote:
>
>> from error log
>>
>> [27-Apr-2015 23:13:22] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/mesotheliomavictimscenter/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>>
>>
>> On Wed, Apr 29, 2015 at 5:31 PM, Benjamin Intal <notifications@github.com
>> > wrote:
>>
>>> In the default config there's a
>>> define('WP_DEBUG', false);
>>> there, so you'll have to remove that. And replace it with
>>> error_reporting(E_ALL); ini_set('display_errors', 1);
>>> define( 'WP_DEBUG', true);
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97620430>
>>> .
>>>
>>
>>
>>
>> --
>> www.DesignByPepper.com
>>
>
>
>
> --
> www.DesignByPepper.com
>



-- 
www.DesignByPepper.com

**Comment by designbypepper** [comment]
ok, apparently one of my many sites was built in concrete and php 5.4 is
not compatable with concrete and so hostmonster is going to upgrade me to
5.4 now and i will see what happens

On Wed, Apr 29, 2015 at 5:40 PM, Pepper <pepperwarren@gmail.com> wrote:

> here is today's error
>
>
> [30-Apr-2015 00:29:02] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/acceleratedheating/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>
>
> On Wed, Apr 29, 2015 at 5:39 PM, Pepper <pepperwarren@gmail.com> wrote:
>
>> that was a few days ago when i tried on another site, let me get today's
>> error, probably the same
>>
>>
>> On Wed, Apr 29, 2015 at 5:36 PM, Pepper <pepperwarren@gmail.com> wrote:
>>
>>> from error log
>>>
>>> [27-Apr-2015 23:13:22] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/mesotheliomavictimscenter/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>>>
>>>
>>> On Wed, Apr 29, 2015 at 5:31 PM, Benjamin Intal <
>>> notifications@github.com> wrote:
>>>
>>>> In the default config there's a
>>>> define('WP_DEBUG', false);
>>>> there, so you'll have to remove that. And replace it with
>>>> error_reporting(E_ALL); ini_set('display_errors', 1);
>>>> define( 'WP_DEBUG', true);
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97620430>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> www.DesignByPepper.com
>>>
>>
>>
>>
>> --
>> www.DesignByPepper.com
>>
>
>
>
> --
> www.DesignByPepper.com
>



-- 
www.DesignByPepper.com

**Comment by designbypepper** [comment]
the plug in now works.   I had to burn a website to do it, but it turns out
because long ago i built a website in concrete, the server detected that
and would not upgrade my php, i was able to manually do it which fixed the
problem.



On Wed, Apr 29, 2015 at 5:45 PM, Pepper <pepperwarren@gmail.com> wrote:

> ok, apparently one of my many sites was built in concrete and php 5.4 is
> not compatable with concrete and so hostmonster is going to upgrade me to
> 5.4 now and i will see what happens
>
> On Wed, Apr 29, 2015 at 5:40 PM, Pepper <pepperwarren@gmail.com> wrote:
>
>> here is today's error
>>
>>
>> [30-Apr-2015 00:29:02] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/acceleratedheating/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>>
>>
>> On Wed, Apr 29, 2015 at 5:39 PM, Pepper <pepperwarren@gmail.com> wrote:
>>
>>> that was a few days ago when i tried on another site, let me get today's
>>> error, probably the same
>>>
>>>
>>> On Wed, Apr 29, 2015 at 5:36 PM, Pepper <pepperwarren@gmail.com> wrote:
>>>
>>>> from error log
>>>>
>>>> [27-Apr-2015 23:13:22] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/mesotheliomavictimscenter/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>>>>
>>>>
>>>> On Wed, Apr 29, 2015 at 5:31 PM, Benjamin Intal <
>>>> notifications@github.com> wrote:
>>>>
>>>>> In the default config there's a
>>>>> define('WP_DEBUG', false);
>>>>> there, so you'll have to remove that. And replace it with
>>>>> error_reporting(E_ALL); ini_set('display_errors', 1);
>>>>> define( 'WP_DEBUG', true);
>>>>>
>>>>> —
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97620430>
>>>>> .
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> www.DesignByPepper.com
>>>>
>>>
>>>
>>>
>>> --
>>> www.DesignByPepper.com
>>>
>>
>>
>>
>> --
>> www.DesignByPepper.com
>>
>
>
>
> --
> www.DesignByPepper.com
>



-- 
www.DesignByPepper.com

**Comment by oherman** [comment]
Indeed it was an old PHP causing the crash. Let us know if you run into
other problems related to Page Builder Sandwich.

**Comment by designbypepper** [comment]
but it killed the concrete site.   i will have to work overnight to rebuild
before client discovers it.   Thanks for your help and maybe that's why
some people are having problems even though they think they are getting the
latest php, they might not be and need to discuss this with their hosting
provider.   Thank you for helping.

On Wed, Apr 29, 2015 at 5:55 PM, Pepper <pepperwarren@gmail.com> wrote:

> the plug in now works.   I had to burn a website to do it, but it turns
> out because long ago i built a website in concrete, the server detected
> that and would not upgrade my php, i was able to manually do it which fixed
> the problem.
>
>
>
> On Wed, Apr 29, 2015 at 5:45 PM, Pepper <pepperwarren@gmail.com> wrote:
>
>> ok, apparently one of my many sites was built in concrete and php 5.4 is
>> not compatable with concrete and so hostmonster is going to upgrade me to
>> 5.4 now and i will see what happens
>>
>> On Wed, Apr 29, 2015 at 5:40 PM, Pepper <pepperwarren@gmail.com> wrote:
>>
>>> here is today's error
>>>
>>>
>>> [30-Apr-2015 00:29:02] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/acceleratedheating/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>>>
>>>
>>> On Wed, Apr 29, 2015 at 5:39 PM, Pepper <pepperwarren@gmail.com> wrote:
>>>
>>>> that was a few days ago when i tried on another site, let me get
>>>> today's error, probably the same
>>>>
>>>>
>>>> On Wed, Apr 29, 2015 at 5:36 PM, Pepper <pepperwarren@gmail.com> wrote:
>>>>
>>>>> from error log
>>>>>
>>>>> [27-Apr-2015 23:13:22] PHP Parse error:  syntax error, unexpected T_FUNCTION in /home1/designc6/public_html/mesotheliomavictimscenter/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 35
>>>>>
>>>>>
>>>>> On Wed, Apr 29, 2015 at 5:31 PM, Benjamin Intal <
>>>>> notifications@github.com> wrote:
>>>>>
>>>>>> In the default config there's a
>>>>>> define('WP_DEBUG', false);
>>>>>> there, so you'll have to remove that. And replace it with
>>>>>> error_reporting(E_ALL); ini_set('display_errors', 1);
>>>>>> define( 'WP_DEBUG', true);
>>>>>>
>>>>>> —
>>>>>> Reply to this email directly or view it on GitHub
>>>>>> <https://github.com/gambitph/Page-Builder-Sandwich/issues/162#issuecomment-97620430>
>>>>>> .
>>>>>>
>>>>>
>>>>>
>>>>>
>>>>> --
>>>>> www.DesignByPepper.com
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> www.DesignByPepper.com
>>>>
>>>
>>>
>>>
>>> --
>>> www.DesignByPepper.com
>>>
>>
>>
>>
>> --
>> www.DesignByPepper.com
>>
>
>
>
> --
> www.DesignByPepper.com
>



-- 
www.DesignByPepper.com

**Comment by oherman** [comment]
Good luck with that and we're glad we are able to help you.

**Comment by bfintal** [comment]
Ah good find. This error means you're using PHP 5.2 or below. Once you set that to PHP 5.3 or higher, then everything should be fine.

If everything in your site's settings say that you're using PHP 5.3+, then please contact HostMonster since this error only appears when it's PHP 5.2 and below.

**Comment by bfintal** [comment]
@oherman Please add this "white screen of death" in the FAQ in http://pbsandwi.ch
