### ISSUE TITLE
Toggle shortcode produces unwanted content field.

### ISSUE THREAD

**Issue by oherman** [gambitph/Page-Builder-Sandwich#163]
While adding new content, toggle shortcode now looks like this:

[pbs_toggle title="Something is wrong" content="What do you mean? You're just dreaming!"]

The normal behavior should be the following:

[pbs_toggle title="Something is wrong"]What do you mean? You're just dreaming![/pbs_toggle]

**Comment by bfintal** [comment]
They changed the behavior of the `content` attribute.

To fix this, see how the google shortcode handles `inner_content`
