### ISSUE TITLE
Acitivation of Page Builder Sandwich crashes my WP-website and Admin Dashboard

### ISSUE THREAD

**Issue by jwfukkink** [gambitph/Page-Builder-Sandwich#168]
When I activate Page Builder Sandwich my website goes blank (no errors just a white screen), and the Wordpress admin dashboard too. I then disable Page Builder Sandwich by renaming its folder (with FTP) and regain access to my website and dashboard.

Wordpress: 4.2.2
theme: Responsive Pro 1.0.1.2

I really like Page Builder Sandwich and use it on another website (Wordpress 4.2) without any problems.Please help!

**Comment by oherman** [comment]
We’d like to see your PHP error logs and see where this is happening. Please also make sure your PHP version is at least 5.3

**Comment by jwfukkink** [comment]
Hi,

Thanks for helping out!

Please be aware of my technology level: can switch on/off computer with
confidence. ;-)

> Please also make sure your PHP version is at least 5.3
That's the first hurdle to take.
My current version is 5.2.17.
I will contact my hosting provider to see when they will upgrade.

Are you sure the 5.3 is mandatory?

Just to be complete: my other website (same hosting provider Strato.com) is
running WP 4.2 and PHP 5.3.29.
Page Builder Sandwich is running fine there.

> We’d like to see your PHP error logs and see where this is happening.
With this one you have to give some hints.
I have FTP access.
Where can I find those logs?
Is there any debugging mode I have to switch on beforehand?

Thanks in advance!


Grtz, JW


2015-05-15 6:40 GMT+02:00 oherman <notifications@github.com>:

> We’d like to see your PHP error logs and see where this is happening.
> Please also make sure your PHP version is at least 5.3
>

**Comment by oherman** [comment]
Now that we know you’re running PHP 5.2, it would be best to get that to 5.3 first.
We’ll go with the logs if ever that doesn’t work.

Let me know how it goes.

**Comment by jwfukkink** [comment]
Hi,

> Now that we know you’re running PHP 5.2, it would be best to get that to
5.3 first.
I checked the support pages of my hosting provider.
It turns out I can set the PHP version myself.

Switched over to PHP 5.3 (actually 5.3.29).
Installed and activated Page Builder Sandwich.
And it runs fine now.

Thanks very much for pushing me in the right direction!

Grtz, JW




2015-05-15 10:53 GMT+02:00 oherman <notifications@github.com>:

> Now that we know you’re running PHP 5.2, it would be best to get that to
> 5.3 first.
> We’ll go with the logs if ever that doesn’t work.
>
> Let me know how it goes.
>
>
