### ISSUE TITLE
Styles enqueued twice and in the footer

### ISSUE THREAD

**Issue by goblindegook** [gambitph/Page-Builder-Sandwich#169]
The same stylesheet file (`css/frontend.css`) is enqueued twice under different handles, `pbsandwich` and `pbsandwich-frontend`, with the latter being included at the end of the document instead of being contained inside the `<head>` tag.

**Comment by oherman** [comment]
Are you sure they are one and the same? The same filename is used for columns as well as for the main.
If it is called twice in a duplicate manner (as in the exact same path), let’s see it with screenshots so it can be addressed.

**Comment by goblindegook** [comment]
Yes, both styles have the same path but different handles. I'm attaching a screenshot of the Inspector pane.

![blog](https://cloud.githubusercontent.com/assets/285497/7790748/70917e80-0289-11e5-9423-0d6ca4e72b58.png)

**Comment by bruno-barros** [comment]
Yeah. Same here.
Beside that, I tried to dequeue, but didn't works. 
Any help?
```
add_action('init', function(){

    wp_deregister_style('pbsandwich-frontend');
    wp_deregister_style('pbsandwich');
    wp_dequeue_style('pbsandwich-frontend');
    wp_dequeue_style('pbsandwich');
});
```

![header](https://cloud.githubusercontent.com/assets/1840784/9150852/7cb104b8-3dc3-11e5-9769-0901d06868d7.jpg)


![footer](https://cloud.githubusercontent.com/assets/1840784/9150855/87a6b4da-3dc3-11e5-9f5f-af69c3d8ed6c.jpg)
