### ISSUE TITLE
Ability to enable/disable default shortcodes available to editor

### ISSUE THREAD

**Issue by maciekkus** [gambitph/Page-Builder-Sandwich#170]
Hi,
I would like to add enhancement idea that is about to allow Page Builder to work in "limited" mode.
In that limited mode developer should be able to:
- disable some default shortcodes (by filters or by settings in admin area)
- available column configurations 
- custom settings for columns, etc.

**Comment by oherman** [comment]
We haven't designed the plugin like this yet. However, we will keep this in mind for a future update.
