### ISSUE TITLE
Wrong link on welcome page

### ISSUE THREAD

**Issue by boluda** [gambitph/Page-Builder-Sandwich#173]
Hi there!

Amazing plugin guys. Just one little thing. Your welcome page links to http://pbsandwi.ch/extensions instead of http://pbsandwi.ch/downloads, and it returns a 404.

Apart from that, pretty slick plugin ;)

**Comment by oherman** [comment]
Thanks for the headsup. We scoured our page here and in pbsandwi.ch and the extensions page link should no longer appear.

Let us know if we missed one.

**Comment by boluda** [comment]
Ok! The only one I saw was this one:

Snapshot -> http://snag.gy/4Hsf1.jpg (links to http://pbsandwi.ch/extensions)

Apart from that, everything fine! :)

**Comment by oherman** [comment]
Ok may I have the URL where you saw this?

**Comment by boluda** [comment]
Yea, sure! The Welcome page showed upon activation :) -> wp-admin/index.php?page=sandwich-about

**Comment by oherman** [comment]
Oh so it's from the plugin. Okay, consider it done. New pull from the git
will fix it.
Fix will come in the update.

**Comment by boluda** [comment]
OK! :)
