### ISSUE TITLE
Users unable to login

### ISSUE THREAD

**Issue by cclagator** [gambitph/Page-Builder-Sandwich#179]
Hi, I love the new version but it messed up my site and I had to disable it. Basically, my users could no longer log in, the login page was sending them to a white page (and they were not logged in). Disabling the PB plugin fixed the issue. I had redesigned two page on the site using the plugin, none were the login page but one of them was the custom profile page. Not sure if that's related or if it was a theme conflict. I'm using the Genesis theme and everything is pretty much up to date.

**Comment by bfintal** [comment]
Hello, this is the old plugin that is no longer being maintained. Are you using the one in wp.org? I would like to continue the conversation via email. Please email me at support@pagebuildersandwich.com

Can you also try updating to the latest version of PB Sandwich, which is version 2.6.1, there are bug fixes regarding an error notice which may appear that can possibly cause this. I'm not too sure without having more info.

If updating doesn't work, can you give me the details of your set up? PHP version, WordPress version, themes & plugins installed via email?
