### ISSUE TITLE
img tag global set to block in css

### ISSUE THREAD

**Issue by almadsen** [gambitph/Page-Builder-Sandwich#180]
In the file "content-tools.min.css" img tags get set to block, this is not css put to good use, you need to make some kind of namespacing for it to not be global and disturb every img tag.

**Comment by bfintal** [comment]
I have discussed this before with CT regarding that one. I agree with you on this one.

Also, for bugs on the lite version, please post on the support tab in the plugin page in the wp.org repo. This repo isn't used anymore :)

I'll close all issues in this repo. But I'll resolve this issue for the next update.
