### ISSUE TITLE
Button Shortcode

### ISSUE THREAD

**Issue by bfintal** [gambitph/Page-Builder-Sandwich#21]
Normal & ghost buttons

Use Bootstrap http://getbootstrap.com/css/#buttons

**Comment by SiamKreative** [comment]
Hey Benjamin,

Why do you want to use a shortcode? I think it goes against the original idea. How about something similar than this: https://wordpress.org/plugins/forget-about-shortcode-buttons/ ?

**Comment by bfintal** [comment]
Because of [Shortcake](https://github.com/fusioneng/Shortcake), so that we don't introduce new UIs.

Yup the original idea was to make columns visible. Although now it's become a builder.

What should be a shortcode vs what should be plain editable html (like the plugin you just shared)?

For columns, I think it clearly should not be shortcodes because 1) they won't look like columns and 2) they won't be readily editable. For contact forms, it's a clear shortcode because of the number of parameters, not to mention we'll re-use the existing Jetpack contact form shortcode.

I'd like to hear what you have in mind :)

**Comment by bfintal** [comment]
Closed #83
