### ISSUE TITLE
Autoembed inside columns not working

### ISSUE THREAD

**Issue by knusperpixel** [gambitph/Page-Builder-Sandwich#25]
If you insert a YouTube URL in the editor, WordPress attempts to embed the Video inside the editor. If you do the same inside a column, nothing happens. Even worse, the video is not displayed in the frontend!

Steps to reproduce:
1. Insert any number of columns
2. Insert a YouTube URL

Expected behaviour:
The preview should appear and the video should be embedded in the frontend.

Actual behaviour:
Only the URL gets displayed.

**Comment by bfintal** [comment]
Did some quick tests:

Inside the column `td`, this doesn't embed properly:

```<p class="ui-sortable-handle">https://www.youtube.com/watch?v=8kkpk9b1az8</p>```

Switching it to this makes it embed:

```<p>https://www.youtube.com/watch?v=8kkpk9b1az8</p>```

Although, switching to text mode, visual mode, then text mode again brings the source back to this then stops the embed from showing up again:

```<p class="ui-sortable-handle">https://www.youtube.com/watch?v=8kkpk9b1az8</p>```

My hunch is that there's something in jQuery sortable that's stopping the embed

**Comment by bfintal** [comment]
Further findings:

Pasting a YT link in an empty normal `table` td cell does not automatically convert to oembed.

**Comment by bfintal** [comment]
Further findings:

In the WP core, the URL **MUST** be placed on a new line or else it won't auto-embed

**Comment by bfintal** [comment]
This also applies to Twitter embeds

**Comment by bfintal** [comment]
We might not just fix this since this appears to be an existing WordPress bug: https://core.trac.wordpress.org/ticket/25387

**Comment by bfintal** [comment]
This can be an alternative: #53
