### ISSUE TITLE
Shortcode parsing does not allow standalone variables (Shortcake issue)

### ISSUE THREAD

**Issue by oherman** [gambitph/Page-Builder-Sandwich#38]
Shortcake can allow and parse variables with values
eg. [mycode src=someplaceinthenet]

but WILL NOT PARSE NOR ALLOW THIS KIND OF CODE
eg. [mycode someplaceintenet]

Called as standalone variables for easier identification, these kinds cannot be easily generated within shortcake.

These standalone variables are parsed as
$attr[0], $attr[1] and so on...

while normal variables are passed as
$attr('src' => 'value')

Shortcake generates values to pass on to shortcodes by this method:

array(
 'label' => 'IFrame embed code',
 'attr' => 'content',
 'type' => 'textarea',
'description' => 'Enter embed code generated from Google Maps.',
),

It has no provisions for sending standalone variables.

A fix for this issue requires a change in shortcake.

**Comment by bfintal** [comment]
This is an unresolved Shortcake issue https://github.com/fusioneng/Shortcake/issues/128

**Comment by bfintal** [comment]
Submitted a fix to Shortcake https://github.com/fusioneng/Shortcake/pull/180

**Comment by bfintal** [comment]
If the pull request goes through, we should remove our own implementation **sandwich-googlemaps** then do a `remove_shortcode` then `add_shortcode` on **googlemaps** to re-implement it. We can end up with 1 shortcode that works with Jetpack's googlemaps shortcode

**Comment by bfintal** [comment]
The new PR to Shortcake: https://github.com/fusioneng/Shortcake/pull/198
