### ISSUE TITLE
Woo Canvas Compatibility

### ISSUE THREAD

**Issue by riceguitar** [gambitph/Page-Builder-Sandwich#40]
There seems to be a conflict between Bootstrap's columns and the wrapper of Woo's Canvas Theme framework. I haven't pinpointed which classes and css rules exactly are breaking the Bootstrap columns and not allowing a 12 column to fit within the row class. Will report back.

**Comment by bfintal** [comment]
Does this happen also with the sandwich master? We namespaced the columns with `.sandwich` to prevent this.

Another possible cause is #41 that was just reported.

**Comment by bfintal** [comment]
Just merged the fix for #41, can you test again with the latest master whether this problem still occurs? If it still does, then `box-sizing` was not the issue.

**Comment by riceguitar** [comment]
Just installed the fix. And it looks like you've got it fixed! Thanks for resolving! So far not finding any further issues with Woo Canvas.

**Comment by riceguitar** [comment]
So found another Canvas conflict. Different, but still an issue with WooCanvas. Woo has its own layout options. 

Correctly displayed should look like this:
https://cloudup.com/cWCYp2jEuVq

With PBS active, it causes this, and the options are no longer selectable:
https://cloudup.com/cE1hPeGm0Ig

Chrome console is showing these errors. These are resolved when PBS is deactivated.

**Comment by bfintal** [comment]
Unfortunately we do not have a copy of WooCanvas that we can work with :( We'll probably need help on this.

What are the console errors that show up? Maybe fixing those can fix the problem.

**Comment by riceguitar** [comment]
Ben, how can I send you the files. I don't want to attach them publicly.

**Comment by riceguitar** [comment]
BUMP

**Comment by bfintal** [comment]
Oh sorry, I didn't notice the reply! bf.intal@gambit.ph :)

**Comment by bfintal** [comment]
Verified that this was a Shortcake issue that got resolved from an update.

Created a PR on this #133, you can test it out on the PR :)

Will very some stuff before merging the PR

**Comment by bfintal** [comment]
Fixed in 1.0.x
