### ISSUE TITLE
dequeue CSS

### ISSUE THREAD

**Issue by FrDH** [gambitph/Page-Builder-Sandwich#48]
Hi, I must say this is probably the cleanest approach for letting clients create grid layouts. Loving it!
I've got only one question: Is there any way I can stop the plugin from including its frontend.css file?
I managed to get rid of the file included in the header, but there still is one (the same file?) included in the footer.
````php
add_action('wp_print_styles', 'dequeue_sandwich_styles');
function dequeue_sandwich_styles()
{
	wp_dequeue_style( 'pbsandwich' );
}
````
Thanks in advance!

**Comment by FrDH** [comment]
As usual, the answer occured to me about a minute after posting the question :-)
Had to add the dqueue_sandwich_styles function to the "get_footer" hook (and add the second file-id):
````php
add_action('wp_print_styles', 'dequeue_sandwich_styles');
add_action('get_footer', 'dequeue_sandwich_styles');
function dequeue_sandwich_styles()
{
    wp_dequeue_style( 'pbsandwich' );
    wp_dequeue_style( 'pbsandwich-frontend' );
}
````

**Comment by bfintal** [comment]
:) :+1:
