### ISSUE TITLE
"Black Studio TinyMCE Widget" not working anymore

### ISSUE THREAD

**Issue by venin** [gambitph/Page-Builder-Sandwich#50]
this happens with the newest version of PB sandwich...

**Comment by bfintal** [comment]
Verified that this is a Shortcake issue, filed https://github.com/fusioneng/Shortcake/issues/185

**Comment by bfintal** [comment]
Pull request for the fix: https://github.com/fusioneng/Shortcake/pull/186

**Comment by bfintal** [comment]
Fixed in v0.9
