### ISSUE TITLE
Columns not spanning the whole width

### ISSUE THREAD

**Issue by bfintal** [gambitph/Page-Builder-Sandwich#51]
reported in https://wordpress.org/support/topic/100-width-not-100?replies=1

Columns max out at 1024, they should fill up the whole width

**Comment by bfintal** [comment]
https://wordpress.org/support/topic/100-width-not-100?replies=3#post-6609271
> Will need more information, I just tried it out and doing a 2 column does fill up the whole available width. There's no 1024px limit in the CSS also. It must be with the theme, the best we can do is find out where exactly this 1024px is being enforced then handle that.

**Comment by riceguitar** [comment]
Just tested this on a custom full width template. Not seeing any issues. Looks to me like this is isolated to a conflict in the Theme's CSS. I'd mark this as resolved unless the user reports back with the site URL or theme.

**Comment by bfintal** [comment]
@riceguitar I agree
