### ISSUE TITLE
[PRO] Conditional Display

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Page-Builder-Sandwich#87]
Conditional display for Desktop, tablets and mobile phones.

1. Row Visibility - Row will be visible or not if using desktop/tablet/mobile phone.
2. Empty Space - Different sizes when using desktop/tablet/mobile phone.

**Comment by bfintal** [comment]
Use the filter `pbs_column_toolbar_post` to add buttons to the column toolbar,
Then use your button action in js:

```
editor.on('toolbar-column-myaction', function(e) {
    ...
});
```
